blank_issues_enabled: false
contact_links:
  - name: Github 讨论组
    url: https://github.com/csplink/csp/discussions
    about: 一些使用问题请到 Discussion 提问。

  - name: csp wiki
    url: https://csplink.github.io/
    about: 有关 csp 的简介与部分使用教程

  - name: QQ 群
    url: https://jq.qq.com/?_wv=1027&k=CWt7TZln
    about: "群号 444093737"
